etcd:
  etcdEndpoints: http://172.18.163.214:2379
  serviceName: uaas
  serviceEndpoint: http://120.79.77.207:8088
  provideService: true

domain:
  serverName: cloud.smallsaas.cn
  mode: single

spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://172.17.0.1:3306/uaas?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat
      schema: classpath*:sql/**/*-schema.sql
      data: classpath*:sql/**/*-data.sql
      initialize: false

logging:
  level: debug
  config: config/logback-spring.xml

am:
  shiro-cache-redis: false
