version: "3"
services:
  etcd-server:
    image: quay.io/coreos/etcd:v3.4.4
    container_name: etcd-server
    command: etcd  -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
    ports:
      - '2379:2379' 

  cloud-api:
    image: zelejs/app-openjre11
    container_name: cloud-api
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cloud-api:/webapps
    #ports:
    #  - '8780:8080'

  cloud-web:
    image: daocloud.io/library/nginx
    container_name: cloud-web
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cloud-web/dist:/usr/share/nginx/html
      - ./cloud-web/logs:/var/log/nginx
      - ./cloud-web/conf.d:/etc/nginx/conf.d

  nginx-gateway:
    image: daocloud.io/library/nginx:latest
    container_name: nginx-gateway
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-gateway/conf.d:/etc/nginx/conf.d
      - ./nginx-gateway/logs:/var/log/nginx
      - ./nginx-gateway/html:/usr/share/nginx/html
    ports:
      - '80:80'
  uaas:
    image: zelejs/app-openjre11
    container_name: console-uaas
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./uaas:/webapps
    ports:
      - '8088:8080'
